name: CI/CD Docker Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # Set up the SSH key for access to the VM
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key stored as a GitHub secret

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@4.204.50.56 << 'EOF'
          set -x
          cd ~/ci-cd || exit  # Navigate to the ci-cd directory
          git pull origin main || exit  # Pull the latest changes from the main branch
          docker-compose down || exit  # Stop and remove the current containers
          docker-compose up --build -d || exit  # Rebuild and start the containers in detached mode
        EOF
